version: '3.7'

services:

  grafana:
    image: grafana/grafana:10.0.2
    container_name: grafana
    environment:
      - GF_SERVER_PROTOCOL=https
      - GF_SERVER_DOMAIN=grafana.leona.pink
      - GF_SERVER_ROOT_URL=https://grafana.leona.pink
      - GF_SERVER_CERT_FILE=/var/lib/grafana/fullchain.pem
      - GF_SERVER_CERT_KEY=/var/lib/grafana/privkey.pem
      - GF_SERVER_ENFORCE_DOMAIN=true
    volumes:
      - /mnt/appdata/grafana:/var/lib/grafana
    restart: unless-stopped
#    ports:
#      - "443:3000"
    user: "472"

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /mnt/appdata/grafana/fullchain.pem:/etc/nginx/certs/fullchain.pem
      - /mnt/appdata/grafana/privkey.pem:/etc/nginx/certs/privkey.pem
    ports:
      - "443:443"
      - "80:80"
    restart: unless-stopped

#  promtail:
#    image: grafana/promtail:2.4.2
#    container_name: promtail
#    volumes:
#      - /var/log:/var/log
#      - /var/lib/docker/containers:/var/lib/docker/containers
#      - /root/homelab/lxc/222-grafana/promtail-config.yml:/etc/promtail/config.yml
#    command: -config.file=/etc/promtail/config.yml
#    restart: unless-stopped
