version: '3.7'

services:

  grafana:
    image: grafana/grafana:8.2.5
    container_name: grafana
    environment:
      - GF_SERVER_PROTOCOL=https
      - GF_SERVER_DOMAIN=grafana.leona.pink
      - GF_SERVER_ROOT_URL=https://grafana.leona.pink
      - GF_SERVER_CERT_FILE=/var/lib/grafana/fullchain.pem
      - GF_SERVER_CERT_KEY=/var/lib/grafana/privkey.pem
      - GF_SERVER_ENFORCE_DOMAIN=true
    volumes:
      - /mnt/appdata/grafana:/var/lib/grafana
    restart: unless-stopped
    ports:
      - "443:3000"
    user: "472"
