version: '3'

services:
  audiobookshelf:
    image: advplyr/audiobookshelf
    ports:
      - 80:80
    volumes:
      - /mnt/bind/media:/audiobooks
      - /mnt/appdata/audiobookshelf/metadata:/metadata
      - /mnt/appdata/audiobookshelf/config:/config
    restart: always
