version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /mnt/appdata/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /mnt/appdata/nginx/fullchain.pem:/etc/nginx/certs/fullchain.pem
      - /mnt/appdata/nginx/privkey.pem:/etc/nginx/certs/privkey.pem
    ports:
      - "443:443"
      - "80:80"
    restart: unless-stopped