version: '3'

services:
  plex:
    image: plexinc/pms-docker:latest
    restart: always
    container_name: PlexMediaServer
    network_mode: "host"
    volumes:
#      - /mnt/nextcloud:/data/nextcloud
      - /mnt/bind/media:/data
      - /mnt/appdata/plexmediaserver:/config
#      - /mnt/plex-transcode:/transcode
    env_file:
      - .env
