apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-db-storage-claim
  namespace: service-nextcloud
  labels:
    app: nextcloud
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
