apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nextcloud-server-ingress
  namespace: service-nextcloud
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nextcloud-server
            port:
              number: 80
