apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nextcloud-server-ingress
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: nextcloud-server
          servicePort: 80
