apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud-db
  labels:
    app: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      pod-label: nextcloud-db-pod
  template:
    metadata:
      labels:
        pod-label: nextcloud-db-pod
    spec:
      containers:
        - name: mariadb
          image: linuxserver/mariadb
          env:
            - name: PUID
              value: "99"
            - name: PGID
              value: "100"
            - name: TZ
              value: Europe/Berlin
            - name: MYSQL_DATABASE
              value: nextcloud
          envFrom:
            - secretRef:
                name: nextcloud-db-secret
          volumeMounts:
            - name: db-storage
              mountPath: /config
              subPath: mysql-data
      volumes:
      - name: db-storage
        persistentVolumeClaim:
          claimName: nextcloud-db-storage-claim
