apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud-server
  labels:
    app: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      pod-label: nextcloud-server-pod
  template:
    metadata:
      labels:
        pod-label: nextcloud-server-pod
    spec:
      containers:
        - name: nextcloud
          image: linuxserver/nextcloud
          volumeMounts:
            - name: data-storage
              mountPath: /data
            - name: config-storage
              mountPath: /config
      volumes:
        - name: data-storage
          persistentVolumeClaim:
            claimName: nextcloud-server-data-storage-claim
        - name: config-storage
          persistentVolumeClaim:
            claimName: nextcloud-server-config-storage-claim
