version: '3'

# https://github.com/shenxn/protonmail-bridge-docker
#
# Setup run
# docker run --rm -it -v /mnt/appdata/protonmail-bridge:/root shenxn/protonmail-bridge init

services:
  protonmail-bridge:
    image: shenxn/protonmail-bridge:latest
    restart: unless-stopped
    container_name: ProtonMailBridge
    volumes:
      - /mnt/appdata/protonmail-bridge:/root
    ports:
      - "1025:25"
      - "1143:143"

  promtail:
    image: grafana/promtail:2.4.2
    container_name: promtail
    volumes:
      - /var/log:/var/log
      - /var/lib/docker/containers:/var/lib/docker/containers
      - /root/homelab/lxc/223-mx/promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml -config.expand-env
    restart: unless-stopped
