version: "3"

services:
  loki:
    image: grafana/loki:2.4.2
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - /root/homelab/lxc/227-loki/loki-config.yml:/etc/loki/local-config.yml
      - /root/appdata/loki:/loki/chunks
    command: -config.file=/etc/loki/local-config.yml
    restart: unless-stopped

  promtail:
    image: grafana/promtail:2.4.2
    container_name: promtail
    volumes:
      - /var/log:/var/log
      - /var/lib/docker/containers:/var/lib/docker/containers
      - /root/homelab/lxc/227-loki/promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml -config.expand-env
    restart: unless-stopped
