templates:
  - '/etc/alertmanager/template/*.tmpl'

route:

  group_by: ['alertname']

  group_wait: 30s

  group_interval: 5m

  repeat_interval: 12h

  receiver: telegram_homelab_warning

  routes:

    - matchers:
        - namespace="homelab"
      receiver: telegram_homelab_warning
      routes:
        - matchers:
            - severity="warning"
        - matchers:
            - severity="critical"
          receiver: telegram_homelab_critical

    - matchers:
        - namespace="smarthome"
      receiver: telegram_smarthome_warning
      routes:
        - matchers:
            - severity="warning"
        - matchers:
            - severity="critical"
          receiver: telegram_smarthome_critical

inhibit_rules:
  - source_matchers: [severity="critical"]
    target_matchers: [severity="warning"]
    # Apply inhibition if the alertname is the same.
    # CAUTION:
    #   If all label names listed in `equal` are missing
    #   from both the source and target alerts,
    #   the inhibition rule will apply!
    equal: [alertname, instance]


receivers:
  - name: 'telegram_homelab_warning'
    telegram_configs:
      - bot_token:
        chat_id:
        message: '{{ template "telegram.warning.message" . }}'
  - name: 'telegram_homelab_critical'
    telegram_configs:
      - bot_token:
        chat_id:
        message: '{{ template "telegram.critical.message" . }}'
  - name: 'telegram_smarthome_warning'
    telegram_configs:
      - bot_token:
        chat_id:
        message: '{{ template "telegram.warning.message" . }}'
  - name: 'telegram_smarthome_critical'
    telegram_configs:
      - bot_token:
        chat_id:
        message: '{{ template "telegram.critical.message" . }}'
