version: '3.7'

services:

  prometheus:
    image: prom/prometheus:v2.47.0
    container_name: prometheus
    volumes:
      - /root/homelab/lxc/226-prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - /root/homelab/lxc/226-prometheus/alert.rules:/etc/prometheus/alert.rules
      - /mnt/appdata/prometheus/:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.size=240GB'
      - '--storage.tsdb.retention.time=365d'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--storage.tsdb.min-block-duration=2h'
      - '--storage.tsdb.max-block-duration=2h'

    ports:
      - 9090:9090
    user: "1000:1000"
    links:
      - alertmanager:alertmanager
    restart: unless-stopped

  alertmanager:
    image: prom/alertmanager:v0.26.0
    container_name: alertmanager
    ports:
      - 9093:9093
    volumes:
      - /root/homelab/lxc/226-prometheus/alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - /root/homelab/lxc/226-prometheus/telegram_templates.tmpl:/etc/alertmanager/template/telegram_templates.tmpl
    restart: unless-stopped
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /mnt/appdata/nginx/prometheus/fullchain.pem:/etc/nginx/certs/fullchain_prom.pem
      - /mnt/appdata/nginx/prometheus/privkey.pem:/etc/nginx/certs/privkey_prom.pem
      - /mnt/appdata/nginx/alertmanager/fullchain.pem:/etc/nginx/certs/fullchain_alert.pem
      - /mnt/appdata/nginx/alertmanager/privkey.pem:/etc/nginx/certs/privkey_alert.pem
    ports:
      - "443:443"
      - "80:80"
    restart: unless-stopped

  blackbox:
    image: prom/blackbox-exporter
    container_name: blackbox-exporter
    ports:
      - 9115:9115
    command:
      - --config.file=/etc/blackbox/blackbox.yml
    volumes:
      - /root/homelab/lxc/226-prometheus/exporter-config/blackbox.yml:/etc/blackbox/blackbox.yml

  pve_exporter:
    image: prompve/prometheus-pve-exporter
    container_name: pve_exporter
    volumes:
      - /root/homelab/lxc/226-prometheus/exporter-config/pve.yml:/etc/pve.yml
    ports:
     - 9221:9221
    restart: unless-stopped

  unpoller:
    container_name: unpoller
    restart: unless-stopped
    image: golift/unifi-poller:latest
    ports:
      - 9130:9130
    env_file:
      - exporter-config/.unpoller.env

  tapo-1:
    build: ../../smarthome/tapo_p110
    image: tapo_p110:latest
    env_file: exporter-config/.tapo-1.env
    container_name: tapo-1
    restart: unless-stopped
    ports:
      - 8000:8000


  tapo-2:
    build: ../../smarthome/tapo_p110
    image: tapo_p110:latest
    env_file: exporter-config/.tapo-2.env
    container_name: tapo-2
    restart: unless-stopped
    ports:
      - 8001:8000


  tapo-3:
    build: ../../smarthome/tapo_p110
    image: tapo_p110:latest
    env_file: exporter-config/.tapo-3.env
    container_name: tapo-3
    restart: unless-stopped
    ports:
      - 8002:8000


  tapo-4:
    build: ../../smarthome/tapo_p110
    image: tapo_p110:latest
    env_file: exporter-config/.tapo-4.env
    container_name: tapo-4
    restart: unless-stopped
    ports:
      - 8003:8000

  tapo-5:
    build: ../../smarthome/tapo_p110
    image: tapo_p110:latest
    env_file: exporter-config/.tapo-5.env
    container_name: tapo-5
    restart: unless-stopped
    ports:
      - 8004:8000

  tapo-6:
    build: ../../smarthome/tapo_p110
    image: tapo_p110:latest
    env_file: exporter-config/.tapo-6.env
    container_name: tapo-6
    restart: unless-stopped
    ports:
      - 8005:8000

  tapo-7:
    build: ../../smarthome/tapo_p110
    image: tapo_p110:latest
    env_file: exporter-config/.tapo-7.env
    container_name: tapo-7
    restart: unless-stopped
    ports:
      - 8006:8000

  tapo-8:
    build: ../../smarthome/tapo_p110
    image: tapo_p110:latest
    env_file: exporter-config/.tapo-8.env
    container_name: tapo-8
    restart: unless-stopped
    ports:
      - 8007:8000

  tapo-9:
    build: ../../smarthome/tapo_p110
    image: tapo_p110:latest
    env_file: exporter-config/.tapo-9.env
    container_name: tapo-9
    restart: unless-stopped
    ports:
      - 8008:8000

  tapo-10:
    build: ../../smarthome/tapo_p110
    image: tapo_p110:latest
    env_file: exporter-config/.tapo-10.env
    container_name: tapo-10
    restart: unless-stopped
    ports:
      - 8009:8000

  tapo-11:
    build: ../../smarthome/tapo_p110
    image: tapo_p110:latest
    env_file: exporter-config/.tapo-11.env
    container_name: tapo-11
    restart: unless-stopped
    ports:
      - 8010:8000

  tapo-12:
    build: ../../smarthome/tapo_p110
    image: tapo_p110:latest
    env_file: exporter-config/.tapo-12.env
    container_name: tapo-12
    restart: unless-stopped
    ports:
      - 8011:8000

#  thanos_store_gateway:
#    container_name: thanos_store_gateway
#    image: thanosio/thanos:v0.23.1
#    volumes:
#      - /root/homelab/lxc/226-prometheus/bucket_config.yml:/etc/thanos/bucket_config.yml
#    command:
#      - 'store'
#      - '--grpc-address=0.0.0.0:10091'
#      - '--http-address=0.0.0.0:10902'
#      - '--data-dir=/tmp/thanos/store'
#      - '--objstore.config-file=/etc/thanos/bucket_config.yml'
#    restart: unless-stopped


#  thanos_sidecar:
#    container_name: thanos_sidecar
#    image: thanosio/thanos:v0.23.1
#    volumes:
#      - /root/homelab/lxc/226-prometheus/bucket_config.yml:/etc/thanos/bucket_config.yml
#      - /mnt/appdata/prometheus/:/prometheus
#    command:
#      - 'sidecar'
#      - '--tsdb.path=/prometheus'
#      - '--prometheus.url=http://prometheus:9090'
#      - '--grpc-address=0.0.0.0:10091'
#      - '--http-address=0.0.0.0:10902'
#      - '--objstore.config-file=/etc/thanos/bucket_config.yml'
#    depends_on:
#        - prometheus
#    restart: unless-stopped


#  thanos_compactor:
#    container_name: thanos_compactor
#    image: thanosio/thanos:v0.23.1
#    volumes:
#      - /root/homelab/lxc/226-prometheus/bucket_config.yml:/etc/thanos/bucket_config.yml
#    command:
#      - 'compact'
#      - '--log.level=debug'
#      - '--data-dir=/data'
#      - '--objstore.config-file=/etc/thanos/bucket_config.yml'
#      - '--wait'
#    restart: unless-stopped

#  thanos_query:
#    container_name: thanos_query
#    image: thanosio/thanos:v0.23.1
#    command:
#      - 'query'
#      - '--grpc-address=0.0.0.0:10091'
#      - '--http-address=0.0.0.0:10902'
#      - '--query.replica-label=replica'
#      - '--store=thanos_sidecar:10091'
#      - '--store=thanos_store_gateway:10091'
#    ports:
#      - 10902:10902
#    depends_on:
#      - thanos_sidecar
#      - thanos_store_gateway
#    restart: unless-stopped

#  ipmi_exporter:
#    build:
#      context: https://github.com/prometheus-community/ipmi_exporter.git#v1.4.0
#    volumes:
#      - ./ipmi_remote.yml:/config.yml:ro    # replace with your own config
#    ports:
#      - 9290:9290                           # bind on 0.0.0.0
#      # - 127.0.0.1:9290:9290               # or bind to specific interface
#    container_name: ipmi_exporter
#
#  promtail:
#   image: grafana/promtail:2.4.2
#   container_name: promtail
#   volumes:
#     - /var/log:/var/log
#     - /var/lib/docker/containers:/var/lib/docker/containers
#     - /root/homelab/lxc/226-prometheus/promtail-config.yml:/etc/promtail/config.yml
#   command: -config.file=/etc/promtail/config.yml -config.expand-env
#   restart: unless-stopped
