version: '3.7'

services:

  prometheus:
    image: prom/prometheus:v2.36.1
    container_name: prometheus
    volumes:
      - /root/homelab/lxc/226-prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - /root/homelab/lxc/226-prometheus/alert.rules:/etc/prometheus/alert.rules
      - /mnt/appdata/prometheus/:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--storage.tsdb.min-block-duration=2h'
      - '--storage.tsdb.max-block-duration=2h'

    ports:
      - 9090:9090
    user: "1000:1000"
    links:
      - alertmanager:alertmanager
    restart: unless-stopped

  alertmanager:
    image: prom/alertmanager:v0.23.0
    container_name: alertmanager
    ports:
      - 9093:9093
    volumes:
      - /root/homelab/lxc/226-prometheus/config.yml:/etc/alertmanager/config.yml
    restart: unless-stopped
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'

  pve_exporter:
    image: prompve/prometheus-pve-exporter
    container_name: pve_exporter
    volumes:
      - /root/homelab/lxc/226-prometheus/pve.yml:/etc/pve.yml
    ports: 
     - 9221:9221
    restart: unless-stopped

  unpoller:
    container_name: unpoller
    restart: unless-stopped
    image: golift/unifi-poller:latest
    ports:
      - 9130:9130
    env_file:
      - .env

#  thanos_store_gateway:
#    container_name: thanos_store_gateway
#    image: thanosio/thanos:v0.23.1
#    volumes:
#      - /root/homelab/lxc/226-prometheus/bucket_config.yml:/etc/thanos/bucket_config.yml
#    command:
#      - 'store'
#      - '--grpc-address=0.0.0.0:10091'
#      - '--http-address=0.0.0.0:10902'
#      - '--data-dir=/tmp/thanos/store'
#      - '--objstore.config-file=/etc/thanos/bucket_config.yml'
#    restart: unless-stopped


#  thanos_sidecar:
#    container_name: thanos_sidecar
#    image: thanosio/thanos:v0.23.1
#    volumes:
#      - /root/homelab/lxc/226-prometheus/bucket_config.yml:/etc/thanos/bucket_config.yml
#      - /mnt/appdata/prometheus/:/prometheus
#    command:
#      - 'sidecar'
#      - '--tsdb.path=/prometheus'
#      - '--prometheus.url=http://prometheus:9090'
#      - '--grpc-address=0.0.0.0:10091'
#      - '--http-address=0.0.0.0:10902'
#      - '--objstore.config-file=/etc/thanos/bucket_config.yml'
#    depends_on:
#        - prometheus
#    restart: unless-stopped


#  thanos_compactor:
#    container_name: thanos_compactor
#    image: thanosio/thanos:v0.23.1
#    volumes:
#      - /root/homelab/lxc/226-prometheus/bucket_config.yml:/etc/thanos/bucket_config.yml
#    command:
#      - 'compact'
#      - '--log.level=debug'
#      - '--data-dir=/data'
#      - '--objstore.config-file=/etc/thanos/bucket_config.yml'
#      - '--wait'
#    restart: unless-stopped

#  thanos_query:
#    container_name: thanos_query
#    image: thanosio/thanos:v0.23.1
#    command:
#      - 'query'
#      - '--grpc-address=0.0.0.0:10091'
#      - '--http-address=0.0.0.0:10902'
#      - '--query.replica-label=replica'
#      - '--store=thanos_sidecar:10091'
#      - '--store=thanos_store_gateway:10091'
#    ports:
#      - 10902:10902
#    depends_on:
#      - thanos_sidecar
#      - thanos_store_gateway
#    restart: unless-stopped

#  ipmi_exporter:
#    build:
#      context: https://github.com/prometheus-community/ipmi_exporter.git#v1.4.0
#    volumes:
#      - ./ipmi_remote.yml:/config.yml:ro    # replace with your own config
#    ports:
#      - 9290:9290                           # bind on 0.0.0.0
#      # - 127.0.0.1:9290:9290               # or bind to specific interface
#    container_name: ipmi_exporter

  promtail:
    image: grafana/promtail:2.4.2
    container_name: promtail
    volumes:
      - /var/log:/var/log
      - /var/lib/docker/containers:/var/lib/docker/containers
      - /root/homelab/lxc/226-prometheus/promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml -config.expand-env
    restart: unless-stopped
