# my global config
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'homelab'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - 'alert.rules'
  # - "first.rules"
  # - "second.rules"

# alert
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.

  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    static_configs:
         - targets: ['localhost:9090']

#  - job_name: 'pve'
#    scrape_interval: 5s
#    static_configs:
#      - targets:
#        - tinyprox1.leona.pink
#        - tinyprox2.leona.pink
#        - tinyprox3.leona.pink
#    metrics_path: /pve
#    params:
#      module: [default]
#    relabel_configs:
#      - source_labels: [__address__]
#        target_label: __param_target
#      - source_labels: [__param_target]
#        target_label: instance
#      - target_label: __address__
#        replacement: pve_exporter:9221  # PVE exporter.

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [ http_2xx ]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
          - https://nextcloud.leona.pink/login
        labels:
          service: "Nextcloud"
      - targets:
          - http://homeassistant.leona.pink:8123
        labels:
          service: "Homeassitant"
      - targets:
          - https://unifi.leona.pink/manage/account/login
        labels:
          service: "Unifi Controller"
      - targets:
          - https://grafana.leona.pink/login
        labels:
          service: "Grafana"
      - targets:
          - http://prometheus.leona.pink:9090/graph
        labels:
          service: "Prometheus"
      - targets:
          - https://fx8350.leona.pink/login
        labels:
          service: "Unraid"
      - targets:
          - https://tinyprox1.leona.pink:8006
        labels:
          service: "Proxmox"
      - targets:
          - http://prometheus.leona.pink:9093
        labels:
          service: "Alertmanager"
    relabel_configs:
      - source_labels: [ __address__ ]
        target_label: __param_target
      - source_labels: [ __param_target ]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115  # The blackbox exporter's real hostname:port.

  - job_name: 'nodes_services'
    scrape_interval: 5s
    static_configs:
      - targets:
        - dns.leona.pink:9100
        - filer.leona.pink:9100
        - fx8350.leona.pink:9100
        - tinyprox1.leona.pink:9100

  - job_name: 'nodes_iot'
    scrape_interval: 5s
    static_configs:
      - targets:
          - enviro1.leona.pink:9100
          - enviro2.leona.pink:9100
          - enviro3.leona.pink:9100
          - breakout1.leona.pink:9100
          - breakout2.leona.pink:9100
          - breakout3.leona.pink:9100

  - job_name: 'tapo_p110'
    scrape_interval: 5s
    static_configs:
      - targets:
        - tapo-1:8000
        - tapo-2:8000
        - tapo-3:8000
        - tapo-4:8000
        - tapo-5:8000
        - tapo-6:8000
        - tapo-7:8000
        - tapo-8:8000
        - tapo-9:8000
        - tapo-10:8000
        - tapo-11:8000
        - tapo-12:8000

  - job_name: 'enviro'
    scrape_interval: 1s
    static_configs:
      - targets:
        - enviro3.leona.pink:8000
        - enviro2.leona.pink:8000

  - job_name: 'breakout'
    scrape_interval: 1s
    static_configs:
      - targets:
        - breakout1.leona.pink:8003
        - breakout2.leona.pink:8003
        - breakout3.leona.pink:8003

  - job_name: 'scd30'
    scrape_interval: 1s
    static_configs:
      - targets:
        - enviro1.leona.pink:8001

#  - job_name: 'ceph'
#    scrape_interval: 5s
#    honor_labels: true
#    static_configs:
#      - targets:
#        - tinyprox1.leona.pink:9283
#        - tinyprox2.leona.pink:9283
#        - tinyprox3.leona.pink:9283

  - job_name: 'unifipoller'
    scrape_interval: 5s
    static_configs:
      - targets:
        - https://unifi.leona.pink:443
    metrics_path: /scrape
    relabel_configs:
     - source_labels: [__address__]
       target_label: __param_target
     - source_labels: [__param_target]
       target_label: instance
     - target_label: __address__
       replacement: unpoller:9130

#  - job_name: 'ipmi'
#    scrape_interval: 1m
#    scrape_timeout: 30s
#    params:
#      module: [dell]
#    static_configs:
#      - targets:
#        - 192.168.66.87
#    metrics_path: /ipmi
#    scheme: http
#    relabel_configs:
#      - source_labels: [__address__]
#        separator: ;
#        regex: (.*)
#        target_label: __param_target
#        replacement: ${1}
#        action: replace
#      - source_labels: [__param_target]
#        separator: ;
#        regex: (.*)
#        target_label: instance
#        replacement: ${1}
#        action: replace
#      - separator: ;
#        regex: .*
#        target_label: __address__
#        replacement: ipmi_exporter:9290
#        action: replace
